import { ProjectConfig } from "@/types/config";

export const BASE_TEMPLATES = {
  "package.json": (config: ProjectConfig) => `{
  "name": "boilr-generated-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.0.0",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    ${config.db === 'supabase' ? '"@supabase/supabase-js": "^2.39.0",' : ''}
    ${config.db === 'prisma' ? '"@prisma/client": "^5.10.0",' : ''}
    ${config.auth === 'clerk' ? '"@clerk/nextjs": "^4.29.9",' : ''}
    ${config.payments === 'stripe' ? '"stripe": "^14.19.0",' : ''}
    "lucide-react": "^0.344.0",
    "clsx": "^2.1.0",
    "tailwind-merge": "^2.2.1"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "eslint": "^8",
    "eslint-config-next": "15.0.0",
    ${config.db === 'prisma' ? '"prisma": "^5.10.0",' : ''}
  }
}`,
  ".env.example": (config: ProjectConfig) => `
# App
NEXT_PUBLIC_APP_URL=http://localhost:3000

${config.db === 'supabase' ? `
# Supabase
NEXT_PUBLIC_SUPABASE_URL=your-supabase-url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-supabase-service-role-key
` : ''}

${config.auth === 'clerk' ? `
# Clerk
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_...
CLERK_SECRET_KEY=sk_test_...
` : ''}

${config.payments === 'stripe' ? `
# Stripe
STRIPE_SECRET_KEY=sk_test_...
STRIPE_WEBHOOK_SECRET=whsec_...
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...
` : ''}
`,
  "README.md": (config: ProjectConfig) => `
# 🚀 Project Generated by Boilr

This project was generated with a custom stack to help you ship faster. Follow these steps to get everything running perfectly.

## 🛠️ Tech Stack
- **Frontend**: ${config.frontend === 'nextjs' ? 'Next.js 15 (App Router)' : 'Remix'}
- **Database**: ${config.db === 'supabase' ? 'Supabase (PostgreSQL)' : config.db === 'prisma' ? 'Prisma + Docker (Postgres)' : 'MongoDB'}
- **Authentication**: ${config.auth === 'supabase' ? 'Supabase Auth' : config.auth === 'clerk' ? 'Clerk' : 'NextAuth'}
- **Payments**: ${config.payments === 'stripe' ? 'Stripe' : 'None'}

---

## 🏃 Quick Start

1. **Clone & Install**:
   \`\`\`bash
   npm install
   \`\`\`

2. **Environment Variables**:
   Copy \`.env.example\` to \`.env.local\` and fill in the values (see [Setup Guides](#-setup-guides) below).
   \`\`\`bash
   cp .env.example .env.local
   \`\`\`

3. **Development**:
   \`\`\`bash
   npm run dev
   \`\`\`

---

## 📖 Setup Guides

${config.db === 'supabase' || config.auth === 'supabase' ? `
### ⚡ Supabase Setup
1. Create a project at [supabase.com](https://supabase.com).
2. Go to **Project Settings > API**.
3. Copy **Project URL** and **anon public** key to \`.env.local\`.
4. (Optional) If using Auth, enable the providers you need in **Authentication > Providers**.
` : ''}

${config.db === 'prisma' ? `
### 🐘 Prisma & Docker Setup
1. Ensure you have **Docker Desktop** installed.
2. Run \`docker-compose up -d\` to start the Postgres container.
3. Run \`npx prisma db push\` to sync your schema with the database.
4. Run \`npx prisma generate\` to update the Prisma Client.
` : ''}

${config.auth === 'clerk' ? `
### 🔐 Clerk Setup
1. Create an application at [clerk.com](https://clerk.com).
2. Follow the "Add Clerk to your Next.js app" guide.
3. Copy the **Publishable Key** and **Secret Key** to \`.env.local\`.
4. Wrap your layout with \`<ClerkProvider>\` (already configured if selected).
` : ''}

${config.payments === 'stripe' ? `
### 💳 Stripe Setup
1. Create a [Stripe account](https://dashboard.stripe.com/register).
2. Get your **Test API Keys** from the dashboard.
3. Copy \`STRIPE_SECRET_KEY\` and \`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY\` to \`.env.local\`.
4. **Webhooks locally**: Install the [Stripe CLI](https://stripe.com/docs/stripe-cli) and run:
   \`\`\`bash
   stripe listen --forward-to localhost:3000/api/webhooks/stripe
   \`\`\`
5. Copy the webhook secret (\`whsec_...\`) to \`STRIPE_WEBHOOK_SECRET\`.
` : ''}

---

## 🚀 Deployment

### ${config.deploy === 'vercel' ? 'Vercel' : 'Manual'}
1. Push your code to GitHub.
2. Link your repository to ${config.deploy === 'vercel' ? '[Vercel](https://vercel.com/new)' : 'your hosting provider'}.
3. **Important**: Add all environment variables from \`.env.local\` to the production settings.
4. Ensure the build command is \`npm run build\`.

---

## 📦 Project Structure
- \`/src/app\`: App router pages and layouts.
- \`/src/components\`: Reusable UI components.
- \`/src/lib\`: Utility functions and third-party clients (Supabase, Stripe, etc.).
${config.db === 'prisma' ? '- `/prisma`: Database schema and migrations.\n' : ''}- \`.github/workflows\`: CI/CD pipelines for automatic deployment.

---

Generated with ❤️ by [Boilr](https://boilr.com)
`,
  "Dockerfile": () => `
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT 3000
CMD ["node", "server.js"]
`,
  "docker-compose.yml": (config: ProjectConfig) => `
version: '3.8'
services:
  ${config.db === 'prisma' ? `
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
  ` : `
  app:
    build: .
    ports:
      - '3000:3000'
  `}
`,
  ".github/workflows/deploy.yml": (config: ProjectConfig) => `
name: Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      ${config.deploy === 'vercel' ? '- name: Deploy to Vercel\n        run: echo "Deploying to Vercel..."' : ''}
`,
};
